### ISSUE TITLE
[4.1] Update callback confusion

### ISSUE THREAD

**Issue by alancwoo** [Laravel-Backpack/docs#147]
Referring to https://github.com/Laravel-Backpack/CRUD/issues/235#issuecomment-634676568

Can the [documentation for the update 'callback'](https://backpackforlaravel.com/docs/4.1/crud-operation-update#callbacks) please be improved to reflect how to properly do this? (Of course please correct me if this is indeed NOT the right way to go about this)

**ExampleCrudController.php**

    public function update()
    {
        $request = request();
        $request->request->add(['new_field' => 'New value']);
        $response = $this->traitUpdate($request);
        return $response;
    }

Using the code from the documentation `$this->crud->request->request->add(...)` was always resulting in Cannot access protected property `Backpack\CRUD\app\Library\CrudPanel\CrudPanel::$request`

**Comment by tabacitu** [comment]
@alancwoo thanks for posting this. Indeed it was one bit of documentation that we forgot to update when moving to Backpack 4.1, where the `request` is `private` instead of `public`, and you have to use the getters and setters. I see the docs have been updated since, and how feature the new ways of doing this:

```php
    $this->crud->getRequest()->request->add(['author_id'=> backpack_user()->id]);
    $this->crud->getRequest()->request->remove('password_confirmation');
    $this->crud->getRequest()->request->add(['author_id'=> backpack_user()->id]);
    $this->crud->getRequest()->request->remove('password_confirmation');
```

They're a bit verbose, but they should do the trick. Let me know if they don't and we'll reopen.

Cheers!
