### ISSUE TITLE
Unclear How to Use Paid License Key

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/docs#158]
I scoured Google and the docs, and was unable to find where the license key goes. I ended up doing a search on the code base for the 'You're using unlicensed software' string to find the code responsible for the key check, and saw it was a config. Maybe we could make it easier for people to know where the code goes?

It's possible an instruction was sent in an email, but I'm on a team and didn't see the email that may have been sent out.

I was also unable to see instructions by logging into the dashboard; I was only able to find the key and no instruction on how to use it.

It's possible I'm blind but I'm not seeing docs on this 😅

**Comment by tabacitu** [comment]
Indeed @zschuessler , the docs don't mention this because it's only something that concerns you once you've purchased Backpack 😄 And we email the instructions upon payment.

If someone does Google this and stumbles upon the issue, here's how this works. There are two places where you can put your Backpack license code:
- (A) inside your .ENV file, as `BACKPACK_LICENSE=xxx`
- (B) inside your `config/backpack/base.php`, at the bottom, you'll find `'license_code' => env('BACKPACK_LICENSE', false),` and you can replace `false` with your license code (wrapped by single quotes)

Option (A) is the recommended one, because there's no point in saving the license code within the code base (in git), and exposing it to whoever has access to the source code. The Backpack license code is only needed _in production_, so the best way is to add an environment variable there.

Hope this clears things up.
Cheers!

PS. If you're till getting bubble notifications after doing the above, it's possible that your config values are cached, so please do a `php artisan config:clear` - that should fix it.

**Comment by tabacitu** [comment]
PS. Maybe wouldn't be a bad idea for us to include instructions on this in the docs. 

@pxpm what do you think of having a new page under About - something like "FAQ" where we can include things that are not necessarily related to the Admin UI or CRUD? Can you think of other things we would put there? I'm thinking we could use that as sort of a knowledge base, so that not only we have a link to give to people instead of answering again and again the same thing, but something that's also searchable in the docs so maybe they don't ask at all. This question is not exactly "frequently" asked but it could prevent it from becoming so 😄 Do you have any "frequently asked questions" which would benefit from this @pxpm ?

**Comment by tabacitu** [comment]
Done, I've just added a FAQ to the docs with the answer above: https://backpackforlaravel.com/docs/4.1/faq#how-do-i-use-the-backpack-license-key-i-purchased-received

**Comment by zschuessler** [comment]
Thanks! 👍
