### ISSUE TITLE
trouble after triyng to install figma template 

### ISSUE THREAD

**Issue by Alpixweb** [Laravel-Backpack/docs#338]
trouble after triyng to install figma template .
https://flareapp.io/share/v5pl8yM5#F139

**Comment by tabacitu** [comment]
It doesn't really make sense to install the Backpack Figma Template. Is is not software, it's a template for the [Figma](https://www.figma.com/) software. So in order to use it:
- you install Figma
- you [download our template](https://backpackforlaravel.com/products/figma-template) (you'll get a .fig file)
- you use our template inside Figma

Please download it, instead of installing it. 

Cheers!
