### ISSUE TITLE
Upgrade Guide never says to re-run `php artisan backpack:install`

### ISSUE THREAD

**Issue by Patabugen** [Laravel-Backpack/Docs#59]
After upgradig from 3.8 I'm missing a couple of files - `BackpackUser.php` and `CheckIfAdmin.php` specifically.

Running :install seems to fix it by putting the missing files in place.

However the upgrade guide never mentions to re-run `php artisan backpack:install` except if if using elFinder.

Should it mention it somewhere? (if so, where?).

**Comment by tabacitu** [comment]
Huh - that's weird. What version did you upgrade from, not from 3.6?

**Comment by Patabugen** [comment]
Ah Sorry - it was 3.4 ! I didn't realise I was further behind than that in this project. I guess I'll go through the 3.4 upgrade guide first.

**Comment by tabacitu** [comment]
Yes please! You're not the only one that got confused by this - I think the requirement didn't stress this enough. I just added a bigger mention at the top of the upgrade guide that you need 3.6, not 3.5 or 3.4, and links to those upgrade guides. Hopefully more people will see it.

To answer your question: no, we don't really need to run ```php artisan backpack:install``` unless you've installed elfinder. That's because by following the upgrade guide you've already done what was important from that command:
- publish assets - done
- publish prologue/alerts assets - not needed; nothing changed;
- migrate - not needed; nothing changed;
- publish user model - not needed; nothing changed;
- publish middleware - not needed; nothing changed;
- elfinder stuff - that's needed if you use it, yes;

Cheers!
